#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Sensor, S2,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          piston,        tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count = 0;

void flip()
{
	resetMotorEncoder(piston);

	while(getMotorEncoder(piston) < 180)
	{
		motor[piston] = 30;
	}
	if(getMotorEncoder(piston) >= 180)
	{
		motor[piston] = 0;
	}
}

void waitForClap()
{
	clearTimer(timer1);

	while(SensorValue(sound) < 60)
	{
	}
	displayBigTextLine(2, "sound: %d",SensorValue(sound));
	if(SensorValue(sound) >= 60)
	{
		count = count + 1;
		while(SensorValue(sound) >= 60)
		{
		}
	}
	if(getTimerValue(timer1) < 1500 && count >= 2)
	{
		flip();
		count = 0;
		clearTimer(timer1);
	}
}

task main()
{
	 while(true)
	 {
	   displayBigTextLine(5, "timer: %d",getTimerValue(timer1));
	   displayBigTextLine(8, "motorSpeed: %d",motor[piston]);

	   waitForClap();
	 }
}
